name: Deploy Azure Infrastructure
# Trigger workflow on pushes to the main branch targeting the infra path,
# or allow manual triggering from the Actions tab
on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**' # Only run automatically if files in infra/ change
  workflow_dispatch: # Allows manual triggering anytime
# Permissions needed for runner environment
permissions:
  id-token: write # Potentially needed by Azure actions internally
  contents: read  # To checkout the code
jobs:
  deploy_infrastructure:
    name: Deploy Bicep Infrastructure
    runs-on: ubuntu-latest # Use a standard Linux runner environment
    steps:
    # Step 1: Check out the repository code so the workflow can access it
    - name: Checkout Code
      uses: actions/checkout@v4
    # Step 2: Log in to Azure using the Service Principal credentials via the 'creds' input
    - name: Login to Azure
      uses: azure/login@v1
      with:
        # Use the 'creds' input method, passing a JSON string with secrets:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        # Keep false unless you specifically need PowerShell Az module later
        enable-AzPSSession: false
    # Step 3: Install Bicep CLI - More robust installation
    - name: Install Bicep CLI
      run: |
        # Download the Bicep CLI installer
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        # Make it executable
        chmod +x ./bicep
        # Move to local bin directory
        sudo mv ./bicep /usr/local/bin/bicep
        # Verify installation
        bicep --version
    # Step 4: Deploy Bicep File using az CLI directly for more control
    - name: Deploy Bicep File
      run: |
        # Validate the template first
        az deployment sub validate \
          --location uksouth \
          --template-file ./infra/main.bicep \
          --parameters ./infra/main.bicepparam \
          --name deploy-smarteaid-infra-${{ github.run_number }}
          
        # Then create the actual deployment
        az deployment sub create \
          --location uksouth \
          --template-file ./infra/main.bicep \
          --parameters ./infra/main.bicepparam \
          --name deploy-smarteaid-infra-${{ github.run_number }}