name: Deploy Azure Infrastructure
# Trigger workflow on pushes to the main branch targeting the infra path,
# or allow manual triggering from the Actions tab
on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**' # Only run automatically if files in infra/ change
  workflow_dispatch: # Allows manual triggering anytime
# Permissions needed for runner environment
permissions:
  id-token: write # Potentially needed by Azure actions internally
  contents: read  # To checkout the code
jobs:
  deploy_infrastructure:
    name: Deploy Bicep Infrastructure
    runs-on: ubuntu-latest # Use a standard Linux runner environment
    steps:
    # Step 1: Check out the repository code so the workflow can access it
    - name: Checkout Code
      uses: actions/checkout@v4
    # Step 2: Log in to Azure using the Service Principal credentials via the 'creds' input
    - name: Login to Azure
      uses: azure/login@v1
      with:
        # Use the 'creds' input method, passing a JSON string with secrets:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        # Keep false unless you specifically need PowerShell Az module later
        enable-AzPSSession: false
    # Step 3: Install Bicep CLI - Explicitly ensure Bicep tooling is available
    - name: Install Bicep CLI
      run: az bicep install
    # Step 4: Deploy Bicep File using ARM deploy action (replacing bicep-deploy-action)
    - name: Deploy Bicep File
      uses: azure/arm-deploy@v1
      with:
        # Deployment target is the subscription
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        region: 'uksouth'
        template: ./infra/main.bicep
        parameters: ./infra/main.bicepparam
        deploymentName: deploy-smarteaid-infra-${{ github.run_number }}