name: Deploy Container to Azure

concurrency:
  group: deploy-container-${{ github.event.inputs.environment || inputs.environment }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (dev1, dev, stg, prod)'
        required: true
        default: 'dev1' # Default value, adjust as needed
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev1, dev, stg, prod)'
        required: true
        type: choice
        options: # <-- Ensure this list matches your desired environment names
          - dev1
          - dev
          - staging
          - prod

jobs:
    deploy-container-infra:
        name: Deploy Container to ${{ github.event.inputs.environment || inputs.environment }}
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment || inputs.environment }} # This now correctly links to 'stg' when selected
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}' 
                enable-AzPSSession: false

            - name: Install/Verify Bicep CLI
              run: |
                echo "Attempting to ensure Bicep CLI is available..."
                az bicep install
                az bicep version
              continue-on-error: true # Allow to continue even if Bicep is already managed by az cli

            - name: Deploy Container App Env
              uses: azure/cli@v1
              with:
                inlineScript:
                 az deployment sub create --name "containerAppEnvDeployDev" --location "uksouth" --template-file ".\infra\containerApp\containerEnv.bicep" --parameters '.\infra\containerApp\params\containerEnvDev.bicepparam' --parameters "parEnv=${{ github.event.inputs.environment || inputs.environment }}"

            - name: Deploy Container App
              uses: azure/cli@v1
              with:
                inlineScript:
                 az deployment sub create --name "containerAppDeployDev" --location "uksouth" --template-file ".\infra\containerApp\containerApp.bicep" --parameters '.\infra\containerApp\params\containerAppDev.bicepparam' --parameters "parEnv=${{ github.event.inputs.environment || inputs.environment }}"
        
            - name: Azure Logout
              run: az logout
              if: always() # Run even if previous steps fail