name: Update Container App

concurrency:
  group: update-container-${{ github.event.inputs.environment || inputs.environment }}
  cancel-in-progress: true

on:
    workflow_call:
      inputs:
        environment:
          description: 'Target environment (dev1, dev, stg, prod)'
          required: true
          default: 'dev1' # Default value, adjust as needed
          type: string
        image_tag:
          description: 'Docker image tag to configure (e.g., latest, commit SHA)'
          required: true
          default: 'latest' # Default value, adjust as needed
          type: string
    workflow_dispatch:
      inputs:
        environment:
          description: 'Target environment (dev1, dev, stg, prod)'
          required: true
          type: choice
          options: # <-- Ensure this list matches your desired environment names
            - dev1
            - dev
            - staging
            - prod
        image_tag:
          description: 'Docker image tag to configure (e.g., latest, commit SHA)'
          required: true
          default: 'latest' # Default value, adjust as needed

jobs:
    deploy-container-infra:
        name: Deploy Container to ${{ github.event.inputs.environment || inputs.environment }}
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment || inputs.environment }} # This now correctly links to 'stg' when selected
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}' 
                enable-AzPSSession: false

            - name: Install/Verify Bicep CLI
              run: |
                echo "Attempting to ensure Bicep CLI is available..."
                az bicep install
                az bicep version
              continue-on-error: true # Allow to continue even if Bicep is already managed by az cli

            - name: Set Subscription
              uses: azure/CLI@v2
              with:
                azcliversion: 2.63.0
                inlineScript:
                  az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        
            - name: Update container app
              uses: azure/CLI@v2
              with:
                azcliversion: 2.63.0
                inlineScript: |
                  az containerapp update --name "ca-sdt-uks-aid-${{ github.event.inputs.environment || inputs.environment }}" --resource-group "rg-sdt-uks-aid-${{ github.event.inputs.environment || inputs.environment }}" --image "acrsdtuksaid${{ github.event.inputs.environment || inputs.environment }}.azurecr.io/backend-api:${{ github.event.inputs.image_tag || inputs.image_tag }}"
        
            - name: Azure Logout
              run: az logout
              if: always() # Run even if previous steps fail